# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

global:
  scrape_interval: 25s

scrape_configs:
  - job_name: "srtelemetry"
    static_configs:
      - targets: ['172.20.20.2:8000','172.20.20.3:8000']
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']